### PR TITLE
Fix figure 4 error

### PR DESCRIPTION
**Pull request by owenchen**
Some modify

### CODE REVIEW

**Comment by iamblue** [comment]
conflict @@

**Comment by owenchen** [comment]
是目錄改變了的原因嗎?

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=c.c.owenchen@gmail.com&idSignature=22

2016-01-10 16:58 GMT+08:00 blue chen notifications@github.com:

**Comment by iamblue** [comment]
對~~

**Comment by iamblue** [comment]
I add bluetooth folder into content/zh-TW/

**Pull request merged**
